<?php
/**
 * @author    Web200 <contact@web200.fr>
 * @copyright 2019 Web200
 * @license   https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @link      https://www.web200.fr/
 */
?>
<?php
/** @var Web200\ImageResize\Block\Cache\Additional $block */
?>
<p>
    <button onclick="setLocation('<?php /* @escapeNotVerified */ echo $block->getCleanResizedImagesUrl() ?>')" type="button">
        <?php /* @escapeNotVerified */ echo __('Flush Resized Images Cache') ?>
    </button>
    <span><?php /* @escapeNotVerified */ echo __('Generated images with ImageResize module') ?></span>
</p>